### ISSUE TITLE
抄袭抄的这么不要脸

### ISSUE THREAD

**Issue by lizzie8023** [zxx1218/oldImage_fix#2]

**Comment by zxx1218** [comment]
哥们儿，我是作者之一

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年12月10日 11:36 |
| 收件人 | zxx1218/oldImage_fix ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [zxx1218/oldImage_fix] 抄袭抄的这么不要脸 (Issue #2) |

https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life

纯照搬还自己毕业设计,还贴联系方式
